#? Use case for daemon sets
#? - Logging, Monitoring, Networking pods deployed on each node
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
    #? Used to deploy pods on specific nodes only
      # nodeSelector:
      #   kubernetes.io/os: linux
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        #? Generally procfs and sysfs are two virtual filesystems which are responsible for allowancs of programs to kernel and access various system information in conveinent way 
        args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
        ports:
        - name: metrics
          containerPort: 9100
        volumeMounts:
        - name: procfs
          mountPath: /host/proc
          readOnly: true
        - name: sysfs
          mountPath: /host/sys
          readOnly: true
      volumes:
      - name: procfs
        hostPath:
          path: /proc
      - name: sysfs
        hostPath:
          path: /sys

#todo : How to delete daemonsets (ds = daemonsets)
# kubectl delete ds node-exporter -> {It will delete all daemonset pods from nodes}
# kubectl delete ds node-exporter --cascade=false -> {delete ds but not delete the pod which was managed by ds}