#? Autoscalers can be of 3 types (Note: This three types can scale-up and scale-down as well)
# 1. HPA (Horizontal Pod Autoscaler) = Increases the no. of replicas
# 2. VPA (Vertical Pod Autoscaler) = Increases the resources of that workload
# 3. CA (Cluster Autoscaler) = Increases the no. of nodes attached to k8s

# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: utility-api
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: utility-api

# Vertical Pod Autoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: utility-api
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: utility-api
  updatePolicy:
    updateMode: "Off" # There are three values -> off(don't apply changes directly), auto(apply changes directly to pods), intial(apply changes to new pods)

# Cluster autoscaler need to be checked out (do it later)