apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa


# To generate a token for service account we can use command as well like [ k create token [service_account_name]] Or using the below file 

---- 
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: test-sa